### ISSUE TITLE
VccCorrection Question

### ISSUE THREAD

**Issue by aiannar974** [Yveaux/Arduino_Vcc#6]
Hello - I want to make sure I understand what I need to do to get the correct values in in the below line.  It looks like I should measure the voltage of the battery power supply for the numerator and then run the code with the ratio = 1.0 and get the denominator and then plug in the respective values.  Is this correct?

const float VccCorrection = 1.0/1.0;  // Measured Vcc by multimeter divided by reported Vcc

Thank you,
AFI

**Comment by Yveaux** [comment]
Yes!
